version: '3.3'
services:
  rasa:
    image: rasa/rasa
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command: run -m models --enable-api --cors "*" --debug
  webchat:
    build:
      context: .
      dockerfile: Dockerfile-webchat
    ports:
      - 8080:80
